### ISSUE TITLE
How to go around an OutOfMemoryError ?

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#147]
Hello, 

Doing a simulation using the drt contribution, The simulation started to run but had an OutOfMemoryError, despite using 16Go of RAM just for Java. How may I solve this problem without adding more RAM ?

[config.xml.txt](https://github.com/matsim-org/matsim-code-examples/files/3284676/config.xml.txt)

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/3284669/logfile.log)

**Comment by michalmac** [comment]
This issue was fixed via: https://github.com/matsim-org/matsim/commit/dc19370a481514725a0fdae879015ff9385cd1dd

The fix is available in MATSim 11

**Comment by PlumeRoberts** [comment]
Thank you very mcuh. I tried running it under MATSim 11, but I get Thousands of error
```ERROR DrtRoutingModule:89 Start and end stop are the same, agent will walk using mode drt_walk.```
Which I do not understand because I used the plans where this occured but now I removed the useless start_time or end time, I still have the errors, despite my agents being like follow:

```xml
<person age="52" id="1">
        <plan>
        <act end_time="07:25:00" type="h" x="650685.5498" y="6862736.6014"/>
        <leg mode="drt"/>
        <act end_time="17:44:12" type="w" x="650685.5498" y="6862736.6014"/>
        <leg mode="drt"/>
        <act type="h" x="650685.5498" y="6862736.6014"/>
        </plan>
</person>
```

Does any one may know the reason of this error ?

[config.xml.txt](https://github.com/matsim-org/matsim-code-examples/files/3285828/config.xml.txt)

**Comment by jfbischoff** [comment]
Hi,
the agent you are showing here has all its activities at the same coordinates. Logically, there is no vehicle called to move him.
Most likely, there's something wrong with you demand (maybe you are using a wrong coordinate transformation)?

Bests

**Comment by PlumeRoberts** [comment]
Hello,

no there isn't any problem with the coordinate transformation , we use a region divided in areas, and so, people going from area 1 to 1 go from the same point to the same point.
But I would like to know if this is what slows down the loading of agents ? the 200'000 take near half an hour just to load.

**Comment by jfbischoff** [comment]
>no there isn't any problem with the coordinate transformation , we use a region divided in areas, and so, people going from area 1 to 1 go from the same point to the same point.

This will get you rather quirky results and possibly over-estimate the pooling effects of agents.  You should consider spreading your activity locations across the zones.

>But I would like to know if this is what slows down the loading of agents ? the 200'000 take near half an hour just to load.
Perhaps your computer is swapping? Really hard to say. 
In general, try to scale down your simulation to initially,  let's say,1 or 5%. Then check that setup is the way you need it to be and only then start productive runs. This will save you a lot of time.

**Comment by PlumeRoberts** [comment]
Thank you for your advice. I am running a simulation with my old parameters, because I want to see if I can at least finish an iteration. But it looks like it won't because of this error:

```
WARN DefaultUnplannedRequestInserter:103 No insertion found for drt request [id=drt_37882][submissionTime=26580.0][rejected=true] from passenger id=10894 fromLinkId=259100
```

I've been having these error for half an hour now, more than 1300 times, and I'd like to know if it is beacause of the error you mentionned or if it come from something else ?

**Comment by jfbischoff** [comment]
This is  a warning, not an error, and it means that no vechicle was found for some passengers. It's nothing bad in itself and the simulation will finish as planned. 

To avoid the problem, try to 
a) increase the fleet size
b) set higher thresholds for detours  (alpha and beta parameters in DRT config)
c) disable rejections.

**Comment by PlumeRoberts** [comment]
I understood the first and second idea but not the third ? what are rejections ?

**Comment by jfbischoff** [comment]
if a passenger cannot be transported, because no vehicle can meet the criteria, the request is rejected. However, you can disable this, in which case the request will be handled, but with longer waiting or detour time. It depends a bit on the kind of transport you are going to simulate.

**Comment by PlumeRoberts** [comment]
we are here simulating DVRP in th kind of UberPool. Autonomous Shared Vehicles.

Where can it be disabled ? In the drt config ?

**Comment by PlumeRoberts** [comment]
I found out the options I needed:
```xml
<!-- Prints detailed warnings for DRT customers that cannot be served or routed. Default is true. -->
<param name="plotDetailedWarnings" value="false" />
<!-- If true, the max travel and wait times of a submitted request are considered hard constraints (the request gets rejected if one of the constraints is violated). If false, the max travel and wait times are considered soft constraints (insertion of a request that violates one of the constraints is allowed, but its cost is increased by additional penalty to make it relatively less attractive). Penalisation of insertions can be customised by injecting a customised InsertionCostCalculator.PenaltyCalculator -->
<param name="requestRejection" value="false" />
```
