### ISSUE TITLE
NSInternalInconsistencyException: 'NSWindow drag regions should only be invalidated on the Main Thread!

### ISSUE THREAD

**Issue by alexanderbachev** [matsim-org/matsim-code-examples#345]
Dear guys,

I am facing yet another issue, this time probably unrelated to the MATSim software. I have recently been working on generating transit data for my project and am trying to run a simulation with pt. Every time I try to run the simulation at the start of QSim, I get a message pop-up about a previous crash (see screenshot), where I can hit reopen or not open. Whatever I click, the program breaks with the following exception:
<img width="532" alt="Screenshot 2020-05-27 at 20 48 52" src="https://user-images.githubusercontent.com/63676508/83054808-a5105300-a05b-11ea-8fef-1a2784ee8404.png">

```
java[2086:40935] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
```
I'll post part of the log bellow, as it is quite long. I get an issue window from macOS as well (see screenshot).
<img width="1162" alt="Screenshot 2020-05-27 at 20 46 37" src="https://user-images.githubusercontent.com/63676508/83054512-2e735580-a05b-11ea-91a2-bec3750b7108.png">

So far I've tried changing things in the config file, running the equil scenario, running the equil scenario on a newly cloned example-project, updating macOS and using the latest JDK 14, but had no success with avoiding that error. Googling didn't help me either. That error seems to originate from a variety of things. Has anybody encountered something similar?

PS: 1. I was trying to use the Schedule Validator from the GUI the other day, as explained in the book, however that option is missing from the GUI Tools menu.
PS: 2. Am I spamming too much the issues section? Is there another place where I can ask questions?

```
2020-05-27 20:31:43,628  INFO Counter:70 [PopulationWriter] dumped person # 8192
2020-05-27 20:31:43,856  INFO PopulationWriter:139 Population written to: scenarios/sofia/output/population_10k_pt/ITERS/it.0/0.plans.xml.gz
2020-05-27 20:31:43,858  INFO Counter:76 [PopulationWriter] dumped person # 10000
2020-05-27 20:31:43,858  INFO PlansDumpingImpl:93 finished plans dump.
2020-05-27 20:31:43,858  INFO ControlerListenerManagerImpl:229 calling notifyBeforeMobsim on org.matsim.core.population.VspPlansCleaner
2020-05-27 20:31:43,872  INFO ControlerListenerManagerImpl:232 [it.0] all ControlerBeforeMobsimListeners called.
2020-05-27 20:31:43,873  INFO PrepareForMobsimImpl:79 Network seems to be multimodal. Create car-only network which is handed over to PersonPrepareForSim.
2020-05-27 20:31:43,873  INFO NetworkImpl:167  node # 1
2020-05-27 20:31:43,873  INFO NetworkImpl:167  node # 4
2020-05-27 20:31:43,873  INFO NetworkImpl:167  node # 16
2020-05-27 20:31:43,873  INFO NetworkImpl:167  node # 64
2020-05-27 20:31:43,873  INFO NetworkImpl:167  node # 256
2020-05-27 20:31:43,874  INFO NetworkImpl:167  node # 1024
2020-05-27 20:31:43,874  INFO NetworkImpl:167  node # 4096
2020-05-27 20:31:43,877  INFO NetworkImpl:167  node # 16384
2020-05-27 20:31:43,881  INFO NetworkImpl:163  link # 1
2020-05-27 20:31:43,881  INFO NetworkImpl:163  link # 4
2020-05-27 20:31:43,881  INFO NetworkImpl:163  link # 16
2020-05-27 20:31:43,881  INFO NetworkImpl:163  link # 64
2020-05-27 20:31:43,881  INFO NetworkImpl:163  link # 256
2020-05-27 20:31:43,882  INFO NetworkImpl:163  link # 1024
2020-05-27 20:31:43,886  INFO NetworkImpl:163  link # 4096
2020-05-27 20:31:43,903  INFO NetworkImpl:163  link # 16384
2020-05-27 20:31:44,000  INFO NetworkImpl:163  link # 65536
2020-05-27 20:31:44,031 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2020-05-27 20:31:44,045 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2020-05-27 20:31:44,057 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2020-05-27 20:31:44,072 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2020-05-27 20:31:44,088 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2020-05-27 20:31:44,103 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2020-05-27 20:31:44,117 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2020-05-27 20:31:44,130 DEBUG NetworkRoutingProvider:75 requesting network routing module with routingMode=car;	mode=car
2020-05-27 20:31:44,144  INFO Counter:70 [PersonPrepareForSim] handled person # 1
2020-05-27 20:31:44,144  INFO Counter:70 [PersonPrepareForSim] handled person # 8
2020-05-27 20:31:44,144  INFO Counter:70 [PersonPrepareForSim] handled person # 4
2020-05-27 20:31:44,144  INFO Counter:70 [PersonPrepareForSim] handled person # 2
2020-05-27 20:31:44,144  INFO Counter:70 [PersonPrepareForSim] handled person # 128
2020-05-27 20:31:44,144  INFO Counter:70 [PersonPrepareForSim] handled person # 64
2020-05-27 20:31:44,145  INFO Counter:70 [PersonPrepareForSim] handled person # 512
2020-05-27 20:31:44,144  INFO Counter:70 [PersonPrepareForSim] handled person # 32
2020-05-27 20:31:44,145  INFO Counter:70 [PersonPrepareForSim] handled person # 1024
2020-05-27 20:31:44,146  INFO Counter:70 [PersonPrepareForSim] handled person # 2048
2020-05-27 20:31:44,144  INFO Counter:70 [PersonPrepareForSim] handled person # 16
2020-05-27 20:31:44,148  INFO Counter:70 [PersonPrepareForSim] handled person # 4096
2020-05-27 20:31:44,145  INFO Counter:70 [PersonPrepareForSim] handled person # 256
2020-05-27 20:31:44,150  INFO Counter:70 [PersonPrepareForSim] handled person # 8192
2020-05-27 20:31:44,151  INFO Counter:76 [PersonPrepareForSim] handled person # 10000
2020-05-27 20:31:44,213  INFO MobsimListenerManager:49 calling addQueueSimulationListener
2020-05-27 20:31:44,213  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimListener
2020-05-27 20:31:44,214  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimInitializedListener
2020-05-27 20:31:44,214  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.contrib.otfvis.OTFVisLiveModule$OTFVisMobsimListener
2020-05-27 20:31:44,214  INFO MobsimListenerManager:49 calling addQueueSimulationListener
2020-05-27 20:31:44,214  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimAfterSimStepListener
2020-05-27 20:31:44,214  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.vis.snapshotwriters.SnapshotWriterManager
2020-05-27 20:31:44,214  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimListener
2020-05-27 20:31:44,214  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimInitializedListener
2020-05-27 20:31:44,214  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimBeforeCleanupListener
2020-05-27 20:31:44,350  WARN QueueWithBuffer:378 Link 10525 too small: enlarge storage capacity from: 0.07654559269617908 Vehicles to: 0.11480690720536418 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,357  WARN QueueWithBuffer:378 Link 12032 too small: enlarge storage capacity from: 0.22988768502837126 Vehicles to: 0.34479704438980263 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,359  WARN QueueWithBuffer:378 Link 13729 too small: enlarge storage capacity from: 0.2639405683135886 Vehicles to: 0.3958712613851358 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,359  WARN QueueWithBuffer:378 Link 13730 too small: enlarge storage capacity from: 0.2639405683135886 Vehicles to: 0.3958712613851358 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,360  WARN QueueWithBuffer:378 Link 13914 too small: enlarge storage capacity from: 0.057034856331995204 Vehicles to: 0.085543729269543 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,360  WARN QueueWithBuffer:378 Link 13915 too small: enlarge storage capacity from: 0.057034856331995204 Vehicles to: 0.085543729269543 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,363  WARN QueueWithBuffer:378 Link 17882 too small: enlarge storage capacity from: 0.08637054384776512 Vehicles to: 0.1295428601900705 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,364  WARN QueueWithBuffer:378 Link 18079 too small: enlarge storage capacity from: 0.1165426467874073 Vehicles to: 0.17479648878409285 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,364  WARN QueueWithBuffer:378 Link 18752 too small: enlarge storage capacity from: 0.13069293166921614 Vehicles to: 0.1960197935640738 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,364  WARN QueueWithBuffer:378 Link 18753 too small: enlarge storage capacity from: 0.13069293166921614 Vehicles to: 0.1960197935640738 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,371  WARN QueueWithBuffer:378 Link 25102 too small: enlarge storage capacity from: 0.08155934370844677 Vehicles to: 0.12232678166111387 Vehicles.  This is not fatal, but modifies the traffic flow dynamics.
2020-05-27 20:31:44,371  WARN QueueWithBuffer:381 Additional warnings of this type are suppressed.
2020-05-27 20:31:44,480  INFO QSimProvider:111 Added MobsimEngine class org.matsim.core.mobsim.qsim.ActivityEngine
2020-05-27 20:31:44,480  INFO QSimProvider:117 Added Activityhandler class org.matsim.core.mobsim.qsim.ActivityEngine
2020-05-27 20:31:44,480  INFO QSimProvider:123 Added DepartureHandler class org.matsim.core.mobsim.qsim.qnetsimengine.VehicularDepartureHandler
2020-05-27 20:31:44,480  INFO QSimProvider:111 Added MobsimEngine class org.matsim.core.mobsim.qsim.qnetsimengine.QNetsimEngine
2020-05-27 20:31:44,481  INFO QSimProvider:111 Added MobsimEngine class org.matsim.core.mobsim.qsim.DefaultTeleportationEngine
2020-05-27 20:31:44,481  INFO QSimProvider:123 Added DepartureHandler class org.matsim.core.mobsim.qsim.DefaultTeleportationEngine
2020-05-27 20:31:44,481  INFO QSimProvider:129 Added AgentSource class org.matsim.core.mobsim.qsim.agents.PopulationAgentSource
2020-05-27 20:31:44,481  INFO MobsimListenerManager:49 calling addQueueSimulationListener
2020-05-27 20:31:44,481  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimBeforeSimStepListener
2020-05-27 20:31:44,481  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimListener
2020-05-27 20:31:44,481  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.qsim.messagequeueengine.MessageQueueEngine
2020-05-27 20:31:44,481  INFO QSimProvider:135 Added MobsimListener class org.matsim.core.mobsim.qsim.messagequeueengine.MessageQueueEngine
2020-05-27 20:31:44,482  INFO QSimProvider:111 Added MobsimEngine class org.matsim.core.mobsim.qsim.pt.TransitQSimEngine
2020-05-27 20:31:44,482  INFO QSimProvider:123 Added DepartureHandler class org.matsim.core.mobsim.qsim.pt.TransitQSimEngine
2020-05-27 20:31:44,482  INFO QSimProvider:129 Added AgentSource class org.matsim.core.mobsim.qsim.pt.TransitQSimEngine
2020-05-27 20:31:44,555  INFO ReconstructingUmlaufBuilder:113 Generating UmlaufStuecke ...
....................................................................................................
...................................................2020-05-27 20:31:44,562  INFO ReconstructingUmlaufBuilder:126 ... done generating UmlaufStuecke
....................................................................................................
...................................................2020-05-27 20:31:44,748  INFO QNetsimEngine:506 Assigned 6934 nodes and 16525 links to QSimEngineRunner #0
2020-05-27 20:31:44,748  INFO QNetsimEngine:506 Assigned 6933 nodes and 16397 links to QSimEngineRunner #1
2020-05-27 20:31:44,748  INFO QNetsimEngine:506 Assigned 6933 nodes and 16531 links to QSimEngineRunner #2
2020-05-27 20:31:44,748  INFO QNetsimEngine:506 Assigned 6933 nodes and 16545 links to QSimEngineRunner #3
2020-05-27 20:31:44,748  INFO QNetsimEngine:506 Assigned 6933 nodes and 16533 links to QSimEngineRunner #4
2020-05-27 20:31:44,917  INFO MobsimListenerManager:49 calling addQueueSimulationListener
2020-05-27 20:31:44,917  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.PlayPauseSimulationControl$PlayPauseMobsimListener
2020-05-27 20:31:44,918  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimAfterSimStepListener
2020-05-27 20:31:44,918  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimBeforeSimStepListener
2020-05-27 20:31:44,918  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimListener
2020-05-27 20:31:44,918  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimBeforeCleanupListener
/Users/alexanderbachev/matsim-example-project/otfsettings.vcfg
2020-05-27 20:31:45,258  INFO EventsManagerImpl:134  event # 1
2020-05-27 20:31:45,260  INFO QNetsimEngine:346 SIMULATION (QNetsimEngine) AT 04:09:00 : #links=0 #nodes=1
2020-05-27 20:31:45,280  INFO QSim:505 SIMULATION (NEW QSim) AT 04:09:00 : #Veh=25156 lost=0 simT=0.0s realT=1s; (s/r): 0.0
2020-05-27 20:31:45,281  INFO Gbl:58 used RAM: 941131264B = 919073kB = 897MB  free: 439843328B = 419MB  total: 1380974592B = 1317MB
2020-05-27 20:31:45,281  INFO EventsManagerImpl:134  event # 4
2020-05-27 20:31:46.800 java[2086:40935] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff395d1be7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff723a95bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff395fa3dc -[NSException raise] + 9
	3   AppKit                              0x00007fff367f8ddc -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff367e0842 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	5   AppKit                              0x00007fff367e02b3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   libnativewindow_macosx.jnilib       0x000000012b4e33fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	7   ???                                 0x000000010fa406b0 0x0 + 4557375152
)
libc++abi.dylib: terminating with uncaught exception of type NSException

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

**Comment by kainagel** [comment]
Indeed not matsim, but an incompatibility between mac os 10.15 and java opengl (jogl).  See here: https://github.com/matsim-org/matsim-libs/issues/972 .  That issue points to a manual work-around; there is unfortunately no "automatic" work around yet.

**Comment by alexanderbachev** [comment]
Thanks for the fast reply, @kainagel ! I hadn't known there is another Issues section under matsim-libs.

I added the two jars manually (same gluegen_937_...), added them to my only module (matsim-example-project) and set them to Runtime:

<img width="1136" alt="Screenshot 2020-05-27 at 23 46 53" src="https://user-images.githubusercontent.com/63676508/83070880-cdf11200-a074-11ea-96cf-5b65582daef3.png">

After reimporting the maven dependencies and starting the simulation, the program breaks at the same place but with another exception:

```
2020-05-27 23:47:02,658  INFO QSim:505 SIMULATION (NEW QSim) AT 04:09:00 : #Veh=25156 lost=0 simT=0.0s realT=1s; (s/r): 0.0
2020-05-27 23:47:02,658  INFO Gbl:58 used RAM: 948462080B = 926232kB = 904MB  free: 521641472B = 497MB  total: 1470103552B = 1402MB
2020-05-27 23:47:02,660  INFO EventsManagerImpl:134  event # 4
2020-05-27 23:47:02,671 ERROR MatsimRuntimeModifications$1:41 Getting uncaught Exception in Thread AWT-EventQueue-0
java.lang.UnsatisfiedLinkError: Can't load library: /Users/alexanderbachev/matsim-example-project/natives/macosx-universal//gluegen_rt
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2630)
	at java.base/java.lang.Runtime.load0(Runtime.java:744)
	at java.base/java.lang.System.load(System.java:1873)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:625)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at org.matsim.vis.otfvis.opengl.drawer.OTFOGLDrawer.createGLCanvas(OTFOGLDrawer.java:329)
	at org.matsim.vis.otfvis.OTFClientLive$1.run(OTFClientLive.java:78)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Am I missing something to load the library?

**Comment by alexanderbachev** [comment]
I had to add the native jars in the same directory as well. That fixed the issue. Thank you for the assistance!

**Comment by Madnex** [comment]
> I had to add the native jars in the same directory as well. That fixed the issue. Thank you for the assistance!

Where (how) exactly did you add the jars? I'm having the exact same problem.

**Comment by alexanderbachev** [comment]
I've downloaded the 2 `jogl-all.jar` and `gluegen-rt.jar` files in my example-project directory and added them as global libraries. (follow the steps from kainagel's comment: https://github.com/matsim-org/matsim-libs/issues/972#issuecomment-619370785 ). Afterwards, download from the same link the jars which are native to your OS and move them in the same directory as the ...-all.jar files. I did that and the issue was resolved.

<img width="882" alt="Screenshot 2020-06-18 at 12 35 01" src="https://user-images.githubusercontent.com/63676508/85005267-35285080-b161-11ea-9283-b1f807800d21.png">

**Comment by Madnex** [comment]
Great it works! Thanks :)

**Comment by kit4a** [comment]
Hello,

I'm a newbie on MATSim: I'm following the 2019 MATSim class from [https://isis.tu-berlin.de/course/view.php?id=16944](url) and have met the same issue you describe here. I've achived the manual fixing steps but still get the same error. I'm running the equil scenario provided within the repository ([https://github.com/matsim-org/matsim-example-project](url)). I tried with several versions of jdk (11, 13, 14, 15), tried with a freshly cloned repo, tried to reboot after adding the global libraries, tried to add the native as global libraries too but nevermind.
I'm on Mac OS X 10.15.6 (19G2021).
Have someone experienced the issue despite fix proposed here? Having some advices?
Here is the end of the log printed in MATSim GUI:
```

2020-10-13 17:17:05,742  INFO MobsimListenerManager:53   assigned class org.matsim.core.mobsim.framework.listeners.MobsimListener to interface org.matsim.core.mobsim.framework.listeners.MobsimListener
2020-10-13 17:17:08,061  INFO EventsManagerImpl:134  event # 1
/Users/melanie.cortina/Documents/GitHub/matsim-example-project/scenarios/equil/otfsettings.vcfg
2020-10-13 17:17:08,081  INFO EventsManagerImpl:134  event # 4
2020-10-13 17:17:08,082  INFO QNetsimEngine:346 SIMULATION (QNetsimEngine) AT 05:58:30 : #links=0 #nodes=1
2020-10-13 17:17:08,082  INFO QSim:531 SIMULATION (NEW QSim) AT 05:58:30 : #Veh=100 lost=0 simT=0.0s realT=2s; (s/r): 0.0
2020-10-13 17:17:08.670 java[919:11359] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff2f58db57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6823b5bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff2f5b634c -[NSException raise] + 9
	3   AppKit                              0x00007fff2c7b05ec -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 310
	4   AppKit                              0x00007fff2c798052 -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 1416
	5   AppKit                              0x00007fff2c797ac3 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 42
	6   libnativewindow_macosx.jnilib       0x000000012977b3fe Java_jogamp_nativewindow_macosx_OSXUtil_CreateNSWindow0 + 398
	7   ???                                 0x0000000110161c90 0x0 + 4564851856
)
libc++abi.dylib: terminating with uncaught exception of type NSException

The simulation did not run properly. Error/Exit code: 134
```


Thank you

**Comment by alexanderbachev** [comment]
Hi, I am not really proficient in that area, but looking at what you did, I can tell you that I just dragged the native jars to global lib directory in the project and it worked. Do you have them in that directory like in the screenshot above? https://github.com/matsim-org/matsim-code-examples/issues/345#issuecomment-645908233

**Comment by kit4a** [comment]
Hi, thank you for your answer. Yes I have them in the global lib directory as you can see in the screenshot below but it had no effect and did'nt change the error message I get when launching a simulation.

<img width="367" alt="intellij matsim-example-prject screen" src="https://user-images.githubusercontent.com/66429270/96000898-b35ae200-0e37-11eb-9572-2c0cfc4c6802.png">
